definitions:
  env_versions: &env_versions
    xcode: 13.3
  triggering:
    push: &push_event
      events:
        - push
  scripts:
    - &installDependencies
      name: Install Dependencies
      script: ./setup.sh
    - &test
      name: Test
      script: fastlane test
workflows:
  ios-mac-pro-workflow:
    name: iOS Mac Pro Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *installDependencies
      - *test
  ios-m1-mac-mini-workflow:
    name: iOS M1 Mac Mini Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *installDependencies
      - *test
